### get all goods and services

GET http://localhost:4000/api/allOrders

### add new good or service to list

POST http://localhost:4000/api/allOrders/new
Content-Type: application/json

{
  "name": "Mineral water",
  "price": 2.99,
  "quantity": 2,
  "description": "Water from ground, carbohydrated",
  "type": "good"
}

### delete new good or service from list

DELETE http://localhost:4000//api/allOrders/delete/60fdae44dcae797bd473ee2d

